# Generated by Django 4.1.3 on 2022-11-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mychatapp", "0003_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=60, null=True)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("born_date", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("friends", models.ManyToManyField(to="mychatapp.friend")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
