# Generated by Django 4.1.3 on 2022-11-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mychatapp", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="msg_receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msg_receiver",
                to="mychatapp.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="msg_sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msg_sender",
                to="mychatapp.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="mychatapp.userprofile"
            ),
        ),
        migrations.DeleteModel(name="Profile",),
    ]
