# Generated by Django 4.1.3 on 2022-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mychatapp", "0007_chatmessage_creation_date_chatmessage_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="subject",
            field=models.CharField(max_length=300),
        ),
    ]
